services:
  palworld:
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://raw.githubusercontent.com/bamcel/palworld-wine/main/assets/palworld.jpg'
      net.unraid.docker.webui: ''
      net.unraid.docker.shell: ''
