networks:
  game_net:
    name: game_net  

services:
  palworld:
    image: ghcr.io/YOUR_GITHUB_USERNAME/palworld-wine:latest
    container_name: palworld
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - game_net
    volumes:
      - /mnt/user/game_server/palworld/game:/palworld
      - /mnt/user/game_server/steamcmd:/steamcmd
      - /mnt/user/game_server/palworld/mods:/mods:ro
      - /mnt/user/game_server/palworld/backups:/backups
    ports:
      - "8211:8211/udp"   # Game port
      - "27015:27015/udp" # Query port
      - "25575:25575/tcp" # RCON
    stop_grace_period: 2m
